### PR TITLE
Upgrade Fluid packages

### PR DESCRIPTION
**Pull request by hishamco**
@lukaskabrt this address some internal bugs in Fluid reported [here](https://github.com/lukaskabrt/PoExtractor/issues/26#issuecomment-607180592), more specifically in `TheAgencyTheme` & `TheBlogTheme`

### CODE REVIEW

**Comment by hishamco** [comment]
@lukaskabrt could you please merge this while it is stopper for the above themes

**Comment by hishamco** [comment]
@agriffard could you please run `PoExtractor` tool on Crowdin to make sure that the extraction of the `TheAgencyTheme` & `TheBlogTheme` works again

**Comment by agriffard** [comment]
I'd rather use it form the nuget package: https://www.nuget.org/packages/PoExtractor.OrchardCore

@lukaskabrt can you please let me know when the latest version is published on NuGet?

**Comment by lukaskabrt** [comment]
@agriffard I have published the latest version to NuGet ... https://www.nuget.org/packages/PoExtractor.OrchardCore/0.3.0-beta3-71077

**Comment by hishamco** [comment]
Thanks a lot @lukaskabrt

**Comment by agriffard** [comment]
Thank you @lukaskabrt , no more errors.

**Pull request merged**
